[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = main
disabled = 0
renderXml = 1
source = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
sourcetype = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational

[WinEventLog://Security]
index = main
disabled = 0

[WinEventLog://System]
index = main
disabled = 0

[WinEventLog://Application]
index = main
disabled = 0
